micronaut:
  application:
    name: demo
#  scan:
#    packages:
#      - com.example.services
#      - com.example.controllers
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowCredentials: true
          allowedMethods:
            - OPTIONS
            - POST
            - PATCH
            - PUT
            - GET
            - DELETE
          exposedHeaders:
            - Access-Control-Allow-Origin
            - Access-Control-Allow-Headers
            - Access-Control-Request-Method
            - Access-Control-Request-Headers
            - Origin
            - Cache-Control
            - Content-Type
#  endpoints:
#    all:
#      enabled: true
#
#endpoints:
#  flyway:
#    enabled: true
#    sensitive: false
#
#flyway:
#  datasource:
#    default:
#      locations: classpath:db/migration

netty:
  default:
    allocator:
      max-order: 3

datasource:
  default:
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password: password

jackson:
  serialization:
    FAIL_ON_EMPTY_BEANS: true
  deserialization:
    FAIL_ON_UNKNOWN_PROPERTIES: true